# Generated by Django 3.0.6 on 2020-05-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='c_img',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='c_job',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='c_life',
            new_name='life',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='c_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='c_votes',
            new_name='votes',
        ),
    ]
